### ISSUE TITLE
Unable to set API password

### ISSUE THREAD

**Issue by h07d0q** [DigitalDJ/tinytinyrss-fever-plugin#14]
I installed and activated the plugin but the form to set the password in the accordion menu is not displayed.

**Comment by meekjt** [comment]
Did you find a solution for this? I'm having the same problem, I'm suspecting it might be a file permissions issue, but haven't figured it out yet.

**Comment by h07d0q** [comment]
Hi, no I did not find a solution, so I switched to FeedMe on my Android device, which does not use the Fever API.

**Comment by meekjt** [comment]
Sounds good, I switched to Miniflux using the Fever API, it's working well.

**Comment by asn1k** [comment]
Anyone know how to solve this problem? It's been annoying me.

**Comment by bosconb** [comment]
same issue,have no idea yet

**Comment by whoiscoos** [comment]
same issue here

**Comment by black-desk** [comment]
same issue

**Comment by black-desk** [comment]
> Anyone know how to solve this problem? It's been annoying me.

change to [this](https://github.com/dasmurphy/tinytinyrss-fever-plugin) solve it

**Comment by qwe7002** [comment]
same issue, I can't log in through the plugin

**Comment by bitsandnumbers** [comment]
Anyone knows why it happens ? It'd be good not to be stuck with 1.4.7 which is years old now.

So to sum up, we can enable  v2.30, the tab shows up but when entering a password nothing's saved and the "password saved" notification does not show up.

I get an error in the logs : 

`Uncaught Error: Call to a member function prepare() on null in /config/www/tt-rss/plugins.local/fever/init.php:67 Stack trace: #0 /config/www/tt-rss/classes/pluginhandler.php(12): Fever->save() #1 /config/www/tt-rss/backend.php(126): PluginHandler->catchall('save') #2 {main} thrown`

Comparing both init.php from 1.4.7 and 2.30 respectively : 

1.4.7

```
function save()
	{
		if (isset($_POST["password"]) && isset($_SESSION["uid"]))
		{
			$result = db_query("SELECT login FROM ttrss_users WHERE id = '" . db_escape_string($_SESSION["uid"]) . "'");
			if ($line = db_fetch_assoc($result))
			{
				$password = md5($line["login"] . ":" . $_POST["password"]);
				$this->host->set($this, "password", $password);
				echo __("Password saved.");
			}
		}
	}
```

2.30

```
    function save()
    {
        if (isset($_POST["password"]) && isset($_SESSION["uid"]))
        {
            $sth = $this->pdo->prepare("SELECT login FROM ttrss_users WHERE id = ?");
            $sth->execute([clean($_SESSION["uid"])]);
            if ($line = $sth->fetch())
            {
                $password = md5($line["login"] . ":" . $_POST["password"]);
                $this->host->set($this, "password", $password);
                echo __("Password saved.");
            }
        }
    }
```

If someone can catch the issue from here ?

**Comment by eric-pierce** [comment]
This should be fixed by #20 - @bitsandnumbers can you confirm?

**Comment by bitsandnumbers** [comment]
Sadly I do not use TTRSS anymore, so I've got no running instance to test from.

Maybe @black-desk or @c0per ?

**Comment by black-desk** [comment]
> Sadly I do not use TTRSS anymore, so I've got no running instance to test from.
> 
> Maybe @black-desk or @c0per ?

sorry I have switched to freshrss

**Comment by creywood** [comment]
Doesn't appear to be working here, first time plugin install. Unsure if there's anything special about my install; I use tt-rss via [YunoHost](https://yunohost.org/).

A couple of screenshots in case they're useful:

![image](https://user-images.githubusercontent.com/31988069/109085010-f7061680-775c-11eb-837a-8ca65c7e9f89.png)

![image](https://user-images.githubusercontent.com/31988069/109085075-1604a880-775d-11eb-954e-337248e0a71d.png)

**Comment by Orca-web** [comment]
When I use `git clone https://github.com/DigitalDJ/tinytinyrss-fever-plugin fever`  to install fever,I'm having the same problem.

After, Manually download [the latest version of the fever](https://github.com/DigitalDJ/tinytinyrss-fever-plugin/releases). Upload `plugins.local`. Everything works fine.

![image](https://user-images.githubusercontent.com/59247295/109105019-10f92680-7768-11eb-8db0-3dea6675ae17.png)

**Comment by morgannunan** [comment]
Exact same problem here. The opening and closing form tags are there but there's nothing inside of it.

**Comment by s3cret** [comment]
Same problem here.

**Comment by eric-pierce** [comment]
@s3cret can you confirm the version of tt-rss you're using? This change: https://git.tt-rss.org/fox/tt-rss/commit/1f43d7916cda16e9680b9087bda1f52934e8f25b in tt_rss changed the function name which prints "hidden" fields. The plugin has been updated to use that new function, but if you're using this plugin with an old version of TTRSS you may need to update your application, as the developer pushed several changes over the past 6 months which broke plugins like this one.

**Comment by D3XX3R** [comment]
My fix for this problem was to update TT-RSS.
I had a 2 year old version of it installed so no wonder this didn't work.

**Comment by WladyX** [comment]
I confirm, i also switched to the new docker version and now it works.

**Comment by eric-pierce** [comment]
@DigitalDJ it sounds like this can be closed!
