### ISSUE TITLE
Plugin has stopped working with latest update to tt-rss

### ISSUE THREAD

**Issue by ansonlos** [DigitalDJ/tinytinyrss-fever-plugin#17]
The plugin is now not working with the latest update to tt-rss. The author of tt-rss is saying that he has renamed several 'internal methods' and if the plugin is using any of these internal method then it would break:

https://community.tt-rss.org/t/syncing-via-fever-api-has-stopped-working/4308/2

Can the plugin be updated with those renamed 'internal methods'? Thanks.

**Comment by SNAEV** [comment]
[16-Feb-2021 14:10:53 UTC] PHP Warning:  require_once(db.php): failed to open stream: No such file or directory in /var/www/html/tt-rss/plugins.local/fever/index.php on line 36

[16-Feb-2021 14:10:53 UTC] PHP Fatal error:  require_once(): Failed opening required 'db.php' (include_path='/var/www/html/tt-rss/plugins.local/fever:/var/www/html/tt-rss:/var/www/html/tt-rss/include:.:/usr/share/pear:/usr/share/php') in /var/www/html/tt-rss/plugins.local/fever/index.php on line 36

**Comment by xyzmos** [comment]
[Fix ](https://cdn.nextrt.com/blog/fever_1613492399555.tar.gz)

**Comment by christianbur** [comment]
In the short term it would be good to fix the bug, in the long term it probably needs a new plugin, because in Reeder 5 Fever is obsolete and no longer recommended. Does anyone know a ttrss plugin with Google Reader Api?

**Comment by eric-pierce** [comment]
It looks like we have a pull request to fix - I haven't tested but the fix looks relatively simple. #18

**Comment by benfishbus** [comment]
> 
> 
> In the short term it would be good to fix the bug, in the long term it probably needs a new plugin, because in Reeder 5 Fever is obsolete and no longer recommended. Does anyone know a ttrss plugin with Google Reader Api?

Or, Reeder could implement native tt-rss api like Fiery Feeds did.

**Comment by eric-pierce** [comment]
The latest pull request from @froks fixes this. I just opened #19 to suppress "Undefined array key" warnings that were piling up in the system log

**Comment by ansonlos** [comment]
Thanks to the fixes by @froks #18 and further cleanup by @eric-pierce #19 the issue has now been resolved.
