### ISSUE TITLE
Password field under the "Fever Emulation" section is missing

### ISSUE THREAD

**Issue by SolidHal** [DigitalDJ/tinytinyrss-fever-plugin#2]
I have a stock tt-rss install, version 15.7. No plugins (besides this one) and no themes. The previously present field to enter the fever password is now missing, as well as all of the text that followed the password field. 

This text used to follow the password field:

> WARNING: The Fever API uses an UNSECURE unsalted MD5 hash. Consider the use of a disposable application-specific password and use HTTPS.
> 
> To login with the Fever API, set your server details in your favourite RSS application to: http://www.solidhal.net/tt-rss/plugins/fever/
> 
> Additional details can be found at https://feedafever.com/api
> 
> Note: Due to the limitations of the API and some RSS clients (for example, Reeder on iOS), some features are unavailable: "Special" Feeds (Published / Tags / Labels / Fresh / Recent), Nested Categories (hierarchy is flattened)

I see the text is still present in init.php however. 

This has been tested in Safari, Firefox, and Google Chrome.

**Comment by DigitalDJ** [comment]
Not sure what the issue is, but 15.7 is unsupported. tt-rss is a rolling release and should be updated regularly. I am not seeing any issues against 17.12 (fc763c8)
