### ISSUE TITLE
Feeds no longer organised by categories in Reeder

### ISSUE THREAD

**Issue by translit** [DigitalDJ/tinytinyrss-fever-plugin#21]
After applying https://github.com/DigitalDJ/tinytinyrss-fever-plugin/issues/17, my feeds are no longer organised by categories in Reeder. What may be causing this?

**Comment by christianbur** [comment]
I can confirm the probem.

- iOS Reeder 5
- MacOS Reeder 4

If you undo this change the problem is fixed. 
https://github.com/DigitalDJ/tinytinyrss-fever-plugin/commit/e76d33de427f938fb3491337d97d0bacb3441422

**Comment by eric-pierce** [comment]
Thanks @translit and @christianbur - I opened pull request #22 to resolve.

**Comment by translit** [comment]
Confirm fixed. Thanks to @eric-pierce.
