### ISSUE TITLE
error on sync with Press 1.5.4

### ISSUE THREAD

**Issue by bookser** [DigitalDJ/tinytinyrss-fever-plugin#3]
tinytinyrss-fever-plugin 2.2.0，
error on sync with Press 1.5.4

**Comment by DigitalDJ** [comment]
I don't have an Android device. Are there any errors in your tt-rss error log?

**Comment by bookser** [comment]
Press Can synchronize star，Unable to synchronize other articles
tt-rss has no error log display
ios is normal

**Comment by bookser** [comment]
Miniflux is very normal under prees
https://github.com/miniflux/miniflux/blob/master/fever/fever.go

**Comment by bookser** [comment]
Miniflux php
https://github.com/miniflux/miniflux-legacy/blob/master/fever/index.php
