### ISSUE TITLE
Cannot access Fever API via Mac (Reeder/ReadKit) or iOS (Unread)

### ISSUE THREAD

**Issue by anunayk** [DigitalDJ/tinytinyrss-fever-plugin#5]
`Uncaught Error: Call to undefined function clean() in /var/www/html/ttrss/plugins.local/fever/fever_api.php:27 Stack trace: #0 /var/www/html/ttrss/plugins.local/fever/fever_api.php(119): FeverAPI->setUser() #1 /var/www/html/ttrss/plugins.local/fever/index.php(68): FeverAPI->before('') #2 {main} thrown`

`Uncaught Error: Call to a member function prepare() on null in /var/www/html/ttrss/plugins.local/fever/init.php:67 Stack trace: #0 /var/www/html/ttrss/classes/pluginhandler.php(12): Fever->save() #1 /var/www/html/ttrss/backend.php(126): PluginHandler->catchall('save') #2 {main} thrown`

I am running tt-rss on Docker using https://github.com/uvatbc/docker-ttrss

**Comment by DigitalDJ** [comment]
Either your tt-rss is not up to date or your directory structure is non-standard and it cannot find tt-rss's config.php.

**Comment by rahulsindc** [comment]
I have this problem as well; using the bitnami AWS AMI

**Comment by DigitalDJ** [comment]
Did you update tt-rss?
