### ISSUE TITLE
Doesn't work with Reeder on iOS or macOS anymore

### ISSUE THREAD

**Issue by changzhiga** [DigitalDJ/tinytinyrss-fever-plugin#6]
Hi, I just met this problem these days when I rebuilt my ttrss on my vps, Reeder just prompted that the email or password I entered was incorrect, I've re-input that password in fever plugin configuration many times but it still didn't work. What can I do to fix this?

Thanks.

<img width="714" alt="xnip2018-08-25_02-19-35" src="https://user-images.githubusercontent.com/16465863/44601227-673f2480-a80e-11e8-8a56-0d23e07e5824.png">

![img_6320](https://user-images.githubusercontent.com/16465863/44601147-20512f00-a80e-11e8-8284-a5ea659db388.jpg)

**Comment by Chandler-Lu** [comment]
you may use wrong versiton,
There's two version in Github.
New: https://github.com/DigitalDJ/tinytinyrss-fever-plugin
Old: https://github.com/dasmurphy/tinytinyrss-fever-plugin

**Comment by Chandler-Lu** [comment]
额好吧应该是国人？
![2018-08-27 11 23 16](https://user-images.githubusercontent.com/18322610/44638886-a5de0600-a9eb-11e8-925a-cc725148126d.jpg)
新版本安装上去应该是这样的。我之前安装成了旧版本，结果出现了你的这个问题。
新版本的plugin位置应该是http://example.com/plugins.local/fever/
也就是fever文件夹应当位于plugins.local目录下。
你要不再检查一下？
-----
Debian 8
PHP 7.2.9 (cli)

**Comment by changzhiga** [comment]
Thank you so much. My problem's been fixed. 🤝
